### ISSUE TITLE
Is there a way to pass a function to transform the rows in a ResultSet?

### ISSUE THREAD

**Issue by jaydeesimon** [layerware/hugsql#42]
In SQLLite, there are no boolean types. You have to represent them as the integers 0 or 1. Is there a way for me to pass a function to a select that will be called on each row of a ResultSet that can transform it in some way? In my case, I can change integers to booleans, etc. Thank you.

**Comment by csummers** [comment]
Yes, assuming you are using the default `clojure.java.jdbc` adapter, you can use the same options that you would use with [clojure.java.jdbc/query](https://clojure.github.io/java.jdbc/#clojure.java.jdbc/query).  An example of the `:as-arrays?` option is provided in the [Advanced Usage](http://www.hugsql.org/#using-advanced) sections of the docs.

You'll want to pass along a hashmap with `:row-fn` for your purposes.

Also, you may want to look into the possibility of an implementation of the [IResultSetReadColumn](https://clojure.github.io/java.jdbc/#clojure.java.jdbc/IResultSetReadColumn) protocol that would transform these faux boolean fields automatically for you upon retrieval from the database.  Since there is no boolean data type in sqlite, you would likely need to depend on a column naming scheme to achieve this.

**Comment by jaydeesimon** [comment]
Thank you for the quick and comprehensive response!
