### ISSUE TITLE
Mention alternative adapters

### ISSUE THREAD

**Issue by Skinney** [layerware/hugsql#6]
My postgres-async adapter is ready for use (https://github.com/Skinney/hugsql-async).
It's easier if people have an easy access list of adapters available. Like the bottom of the readme.

**Comment by csummers** [comment]
This is great!  I look forward to giving it a go!

I'm currently working on a documentation site since the README is getting a bit long.  New docs will roll with 0.3.0 in a day or so with good navigation (table of contents), and there will definitely be an Adapter section with a link to your adapter in it.

**Comment by Skinney** [comment]
Awesome

**Comment by csummers** [comment]
Well, it took longer than a day, but this is now up on the new doc site that went live with the 0.3.0 release:  [hugsql.org] (http://hugsql.org)

**Comment by Skinney** [comment]
Just read through the documentation. Awesome work!
