### ISSUE TITLE
Interested in a PR for this macro?

### ISSUE THREAD

**Issue by rsslldnphy** [layerware/hugsql#67]
Hi, we really like HugSQL, however have found that often we need a little plain Clojure to wrap a bit of functionality around the returned values, and usually there's no good name for that function that's distinct from the HugSQL one.

We've tried a few approaches to dealing with this - namely having naming conventions, where HugSQL functions always start with an underscore, as well as by defining the HugSQL functions in a separate namespace (that only defines sql functions). The latter is a bit more readable and easier to enforce, but it does mean creating a bunch of nearly empty boilerplate namespaces.

Despite thinking magic macros are generally a bad idea, I found myself writing one to hide away the boilerplate. I've pasted it, along with a usage example, below. Just wondering if you'd like a PR with a cleaned up and more generically usable version? (some of the stuff in here is specific to our use case). Maybe called `def-db-ns` or something?

```clojure
(defmacro defsql
  [& args]
  (let [files (vec (drop-last 2 args))
        alias (last args)]
    `(let [current-namespace# *ns*
           query-namespace#   (symbol (str (ns-name *ns*) ".sql"))]
       (create-ns query-namespace#)
       (in-ns query-namespace#)
       (require '[hugsql.core :as hugsql])
       (doseq [file# ~files]
         (hugsql/def-db-fns file# {:command-options [{:identifiers identity}]}))
       (in-ns (ns-name current-namespace#))
       (alias '~alias query-namespace#))))

;;; usage
(defsql "my-project/sql/foo.sql" :as q)
(q/my-db-fn ,,,)
```

**Comment by csummers** [comment]
@rsslldnphy Thanks for the request.

I understand the boilerplate issue...I have a few projects with some mostly empty db-related namespaces.

However, it looks like this macro is really an "only call this once in your project" kind of macro.  Because its primary function is to create a namespace and then define HugSQL functions (parsing the SQL files), it really should not be called more than once.

If users are using this to grab hold of an alias for a query namespace, it seems like this would encourage the calling of this macro in every namespace that needed queries.  That could be a lot of unnecessary parsing of the same SQL file over and over.

Despite the boilerplate namespace files, the grabbing hold of a namespace alias is exactly what is already available to us in the `:require` part of `ns`.

Your thoughts?  Convince me otherwise?

**Comment by rsslldnphy** [comment]
Ah, this may be something specific to how we structure our projects then. We split our apps into vertical slices which don't share SQL (except for some key, common functionality, which is shared between these slices and has its _own_ SQL.

So a typical project structure looks something like this:

```
src/
  project/
    foo/
      handlers.clj
      queries.clj
      queries.sql
      routes.clj
      schema.clj
    bar/
      handlers.clj
      queries.clj
      queries.sql
      routes.clj
      schema.clj
```

So usually a SQL file is only ever required in one Clojure file (the relevant `handlers.clj`) - and to prevent clashes with functions in the namespace that uses it we create the empty `queries.clj` namespace for each one.

If more than one namespace called this macro with the same SQL file, it would create two different generated namespaces containing the same functions, which I guess is a bit wasteful but I think would at least work. But I won't be horribly upset if this doesn't fit in hugsql! It's easy enough to add to our projects to cater to our particular needs :-)
