### ISSUE TITLE
how to rebind-connection a sql file

### ISSUE THREAD

**Issue by vinurs** [layerware/hugsql#85]
int my project, we can use
(conman/bind-connection *db* "sql/queries.sql")
to bind a sql file to a connection,
but, when i compile the project to a jar package, and run it, then i connect to the server by nrepl and when i modify the sql, so how can i rebind the sql file to the connection?

**Comment by csummers** [comment]
Conman wraps HugSQL's [map-of-db-fns](http://layerware.github.io/hugsql/hugsql.core.html#var-map-of-db-fns), which has the following usage:

```
Usage:

(map-of-db-fns file options?)

where:
 - file is a string file path in your classpath,
   a resource object (java.net.URL),
   or a file object (java.io.File)
 - options (optional) hashmap:
   {:quoting :off(default) | :ansi | :mysql | :mssql
    :adapter adapter }
```

So, feasibily with conman, the `file` argument should be able to take a `java.io.File`, which can be a file outside of your resources/classpath.  This is likely what you need to use instead of string file path.  Something like this:

```clj
(conman/bind-connection db (clojure.java.io/file "/path/to/queries.sql"))
```

HOWEVER, I'm not sure if this works with conman or not.  If it doesn't, maybe it should and that would be an issue for conman.  I'd be interested in knowing if this works.  Thanks!

**Comment by vinurs** [comment]
@csummers thanks very, this doesn't work, it outputs:
1. Unhandled java.lang.ClassCastException
   clojure.lang.PersistentList cannot be cast to java.lang.String
