### ISSUE TITLE
Transformation Function

### ISSUE THREAD

**Issue by MafcoCinco** [layerware/hugsql#92]
Would it be possible to support a user-supplied transformation function?  I know that SQL Korma, for example, allows the user to specify a function that should be run any time data is written to the database and also any time data is queried from the database.

The most obvious usage of this would be key conversion.  Where I currently work, the results of a database query that get returned to our Clojure code is map containing `"snake_cased_strings"`.  Every query function we write requires that we convert to `:kebab-cased-keywords` and sometimes people forget to do this.

If we could provide a conversion function when we set up the database connection or even as a standard option passed to each query, it would make this task much less burdensome.

The other potential use case I thought of was query logging via something like Data Dog, though I'm not 💯 using non-pure functions in this context.

**Comment by conan** [comment]
This can be done using `hugsql.core/hugsql-result-fn`.  Here's what we use to kebab-case keys (using [camel-snake-kebab](https://clj-commons.org/camel-snake-kebab/)) and convert subclasses of `java.util.Date` to `java.time.LocalDateTime` (using [clojure.java-time](https://github.com/dm3/clojure.java-time)):
``` clojure
(defn kebab-case-keys
  "Converts all the keys in the given map to kebab-case"
  [m]
  (cske/transform-keys csk/->kebab-case-keyword m))

(defn inst->local-date-time
  "Converts all the java.util.Dates in the given map to java.time.LocalDateTimes"
  [m]
  (walk/postwalk #(if (inst? %) (date/inst->local-date-time %) %) m))

(defn result-one-format
  [this result options]
  (->> (hsqla/result-one this result options)
       kebab-case-keys
       inst->local-date-time))

(defn result-many-format
  [this result options]
  (->> (hsqla/result-many this result options)
       (map kebab-case-keys)
       (map inst->local-date-time)))

(defmethod hsqlc/hugsql-result-fn :1 [_sym] 'ic.db/result-one-format)
(defmethod hsqlc/hugsql-result-fn :one [_sym] 'ic.db/result-one-format)
(defmethod hsqlc/hugsql-result-fn :* [_sym] 'ic.db/result-many-format)
(defmethod hsqlc/hugsql-result-fn :many [_sym] 'ic.db/result-many-format)
```
By registering your own multimethod implementations for `hugsql-result-fn` for different types of result, you can alter how the results are given back to you.  The same can be done for data going into the database, using `hugsql.core/hugsql-command-fn`.

**Comment by MafcoCinco** [comment]
Sweet!  I will close my PR related to this.  Thanks for your help @conan

**Comment by csummers** [comment]
@conan Thanks for your detailed explanation.  I think this is typically what users are doing for this kind of key transformation issue.  I've also seen other implementations that use the 4th argument of a HugSQL-generated function in order to pass options down into the underlying jdbc library: `clojure.java.jdbc` by gives you a `:result-set-fn` option.

@MafcoCinco Marcus, sorry for the slow reply.  Conan's answer is probably the best solution for this with the current library.

However, this question (or related questions) come up often enough that I think it speaks to the need for at least more documentation about how to solve this.  And, possibly, either a built-in option or separate clojar with this functionality made available as an option to the user.

https://github.com/layerware/hugsql/issues/21
https://github.com/layerware/hugsql/issues/40
https://github.com/layerware/hugsql/issues/48
https://github.com/layerware/hugsql/issues/62

All of the above is for the "from-database-to-result" (outgoing) case.  I'm less convinced of the need for an incoming case, where parameter keys would be transformed, because you can already use kebab style parameter names in a HugSQL SQL statement:  `where id = :v:my-kebab-id`

**Comment by MafcoCinco** [comment]
@csummers I agree WRT the input side.  Seems much less necessary than on the way out due to the syntax of HugSQL.
